# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
    """Calculation of two numbers x and y and returns a result
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sum = channel.unary_unary(
                '/calculator.Calculator/Sum',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                )
        self.Sub = channel.unary_unary(
                '/calculator.Calculator/Sub',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                )
        self.Mult = channel.unary_unary(
                '/calculator.Calculator/Mult',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                )
        self.Div = channel.unary_unary(
                '/calculator.Calculator/Div',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                )


class CalculatorServicer(object):
    """Calculation of two numbers x and y and returns a result
    """

    def Sum(self, request, context):
        """Add of x + y
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sub(self, request, context):
        """Subtraction of x - y
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mult(self, request, context):
        """Multiplication of x * y
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Div(self, request, context):
        """Division of x / y
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sum': grpc.unary_unary_rpc_method_handler(
                    servicer.Sum,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Sub': grpc.unary_unary_rpc_method_handler(
                    servicer.Sub,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Mult': grpc.unary_unary_rpc_method_handler(
                    servicer.Mult,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Div': grpc.unary_unary_rpc_method_handler(
                    servicer.Div,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Calculation of two numbers x and y and returns a result
    """

    @staticmethod
    def Sum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Sum',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Sub',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Mult',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Div',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
