# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\")\n\x11\x43\x61lculatorRequest\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\r2\xa5\x02\n\nCalculator\x12\x44\n\x03Sum\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12\x44\n\x03Sub\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12\x45\n\x04Mult\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12\x44\n\x03\x44iv\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CALCULATORREQUEST']._serialized_start=32
  _globals['_CALCULATORREQUEST']._serialized_end=73
  _globals['_CALCULATORRESPONSE']._serialized_start=75
  _globals['_CALCULATORRESPONSE']._serialized_end=111
  _globals['_CALCULATOR']._serialized_start=114
  _globals['_CALCULATOR']._serialized_end=407
# @@protoc_insertion_point(module_scope)
